/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	alibabacloudv1 "github.com/tiancheng92/alibabacloud/v1"
	versioned "github.com/tiancheng92/alibabacloud/v1/clientset/versioned"
	internalinterfaces "github.com/tiancheng92/alibabacloud/v1/informers/externalversions/internalinterfaces"
	v1 "github.com/tiancheng92/alibabacloud/v1/listers/alibabacloud/v1"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AlbConfigInformer provides access to a shared informer and lister for
// AlbConfigs.
type AlbConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.AlbConfigLister
}

type albConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAlbConfigInformer constructs a new informer for AlbConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAlbConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAlbConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAlbConfigInformer constructs a new informer for AlbConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAlbConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AlibabacloudV1().AlbConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AlibabacloudV1().AlbConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&alibabacloudv1.AlbConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *albConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAlbConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *albConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&alibabacloudv1.AlbConfig{}, f.defaultInformer)
}

func (f *albConfigInformer) Lister() v1.AlbConfigLister {
	return v1.NewAlbConfigLister(f.Informer().GetIndexer())
}
