/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	v1 "github.com/tiancheng92/alibabacloud/v1"
	scheme "github.com/tiancheng92/alibabacloud/v1/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AlbConfigsGetter has a method to return a AlbConfigInterface.
// A group's client should implement this interface.
type AlbConfigsGetter interface {
	AlbConfigs(namespace string) AlbConfigInterface
}

// AlbConfigInterface has methods to work with AlbConfig resources.
type AlbConfigInterface interface {
	Create(ctx context.Context, albConfig *v1.AlbConfig, opts metav1.CreateOptions) (*v1.AlbConfig, error)
	Update(ctx context.Context, albConfig *v1.AlbConfig, opts metav1.UpdateOptions) (*v1.AlbConfig, error)
	UpdateStatus(ctx context.Context, albConfig *v1.AlbConfig, opts metav1.UpdateOptions) (*v1.AlbConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.AlbConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.AlbConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AlbConfig, err error)
	AlbConfigExpansion
}

// albConfigs implements AlbConfigInterface
type albConfigs struct {
	client rest.Interface
	ns     string
}

// newAlbConfigs returns a AlbConfigs
func newAlbConfigs(c *AlibabacloudV1Client, namespace string) *albConfigs {
	return &albConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the albConfig, and returns the corresponding albConfig object, and an error if there is any.
func (c *albConfigs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.AlbConfig, err error) {
	result = &v1.AlbConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("albconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AlbConfigs that match those selectors.
func (c *albConfigs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.AlbConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.AlbConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("albconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested albConfigs.
func (c *albConfigs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("albconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a albConfig and creates it.  Returns the server's representation of the albConfig, and an error, if there is any.
func (c *albConfigs) Create(ctx context.Context, albConfig *v1.AlbConfig, opts metav1.CreateOptions) (result *v1.AlbConfig, err error) {
	result = &v1.AlbConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("albconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(albConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a albConfig and updates it. Returns the server's representation of the albConfig, and an error, if there is any.
func (c *albConfigs) Update(ctx context.Context, albConfig *v1.AlbConfig, opts metav1.UpdateOptions) (result *v1.AlbConfig, err error) {
	result = &v1.AlbConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("albconfigs").
		Name(albConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(albConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *albConfigs) UpdateStatus(ctx context.Context, albConfig *v1.AlbConfig, opts metav1.UpdateOptions) (result *v1.AlbConfig, err error) {
	result = &v1.AlbConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("albconfigs").
		Name(albConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(albConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the albConfig and deletes it. Returns an error if one occurs.
func (c *albConfigs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("albconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *albConfigs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("albconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched albConfig.
func (c *albConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.AlbConfig, err error) {
	result = &v1.AlbConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("albconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
